150 - Show article source in MDX
polubis/WebBlog pull request #221
Opened 2023-04-28 16:54 UTC by TomaszMarczak

Changed GA event to "article_source_clicked" for consistency
Known bug: Article source not showing properly on first article: "Loops in JavaScript and their performance".
![image](https://user-images.githubusercontent.com/35048240/235207681-db100acb-f644-4c7d-9836-ea3c36f991a3.png)

2023-04-29 08:12 UTC, polubis requested changes
Great work one bug to fix and one improvement required

2023-04-29 08:12 UTC, polubis commented on src/components/article/Article.tsx
> +  const articleSource = rawBody.replace(/^(---\s*\n[\s\S]*?\n?)?---\s*\n/, "")
This must be performed ArticleSource component to avoid doing that in Articles

2023-05-03 05:24 UTC, polubis approved these changes
I remember that there was a problem with PL articles, yup?  We can solve it on call but code itself is great, good work mate!

2023-05-03 09:43 UTC, TomaszMarczak commented
Issue was with 2 articles, where modal was broken: "Use Fetch Hook" and "Improving SEO with Ahrefs"
PL articles are working properly.

2023-05-05 07:21 UTC, polubis approved these changes
LGTM - > please add small fix and I'll merge that. Looks good during testing. Good job

2023-05-05 07:21 UTC, polubis commented on src/components/article/TranslatedArticlePage.tsx
> +                style={{ marginRight: "auto" }}
Don't use inline styles. Add it to BottomNavigation styled. Mixing inline with not inline approach can create problem with maintenance later.

2023-05-06 06:35 UTC, merged