Add option to go to article via article title
polubis/WebBlog pull request #222
Opened 2023-04-28 18:41 UTC by Pawel-Gnat

I wrapped the title with a link component and gave the property color: theme.primary (red).

2023-04-29 08:08 UTC, polubis requested changes

2023-04-29 08:08 UTC, polubis commented on src/components/article/Tile.tsx
> +    color: ${theme.primary};
Apply only there.primary when user clicked link -> underline color, In other case it must be white. We need to follow 60% 30% 10% convention in our app with colors

2023-05-02 10:03 UTC, Pawel-Gnat commented
I have updated my repo with necessary changes. Now title links have text decoration set to none, and  text-decoration: underline ${theme.primary} on hover/active state.

2023-05-03 05:29 UTC, polubis approved these changes
Great work mate! Merged

2023-05-03 05:30 UTC, merged